name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to push back to PR branches

      - name: Set up GitHub CLI
        uses: cli/gh-action@v2

      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

      - name: Update .nimble version in release PR branch
        if: steps.release.outputs.pr != ''
        run: |
          set -euo pipefail

          PR_NUMBER="${{ steps.release.outputs.pr }}"
          VERSION="${{ steps.release.outputs.version }}"

          echo "Resolving PR branch for PR #$PR_NUMBER"
          PR_BRANCH=$(gh pr view "$PR_NUMBER" --json headRefName -q .headRefName)

          if [ -z "$PR_BRANCH" ]; then
            echo "Error: Failed to resolve PR branch name"
            exit 1
          fi

          echo "Fetching PR branch: $PR_BRANCH"
          git fetch origin "$PR_BRANCH"
          git checkout "$PR_BRANCH"

          echo "Updating .nimble file to version $VERSION"
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" ./nmgr.nimble

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add ./nmgr.nimble
          git commit -m "chore: bump .nimble version"
          git push origin "$PR_BRANCH"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
